"""add gender field to product

Revision ID: fcf74dae914f
Revises: 13ee041c1a6e
Create Date: 2026-05-21 16:47:31.825840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf74dae914f'
down_revision: Union[str, Sequence[str], None] = '13ee041c1a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    gender_enum = sa.Enum('man', 'woman', 'kid', name='genderenum')
    gender_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('products', sa.Column('gender', sa.Enum('man', 'woman', 'kid', name='genderenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'gender')

    gender_enum = sa.Enum('man', 'woman', 'kid', name='genderenum')
    gender_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
